# Generated by Django 6.0.8 on 2026-09-07 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=150)),
                ('term', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter')], max_length=10)),
                ('year', models.PositiveSmallIntegerField()),
                ('office_hours', models.TextField(blank=True)),
                ('meeting_schedule', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['course_code'],
            },
        ),
        migrations.CreateModel(
            name='AcademicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('assignment', 'Assignment'), ('quiz', 'Quiz'), ('exam', 'Exam'), ('project', 'Project'), ('reading', 'Reading'), ('presentation', 'Presentation'), ('discussion', 'Discussion'), ('lab', 'Lab'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('estimate_source', models.CharField(choices=[('ai', 'AI Estimated'), ('manual', 'User Entered'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('source', models.CharField(choices=[('ai', 'AI Extracted'), ('manual', 'Manually Added')], default='manual', max_length=10)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='todo', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'ordering': ['scheduled_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GradeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('points_earned', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('points_possible', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('weight_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_extra_credit', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudyTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tool_type', models.CharField(choices=[('study_guide', 'Study Guide'), ('practice_questions', 'Practice Questions'), ('summary', 'Summary'), ('other', 'Other')], max_length=30)),
                ('source_text', models.TextField(blank=True)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='study_materials/')),
                ('custom_instructions', models.TextField(blank=True)),
                ('generated_content', models.TextField(blank=True)),
                ('generation_status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('related_events', models.ManyToManyField(blank=True, to='courses.academicevent')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='syllabi/')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_error', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('user', 'course_code', 'term', 'year'), name='unique_course_per_user_term'),
        ),
        migrations.AddConstraint(
            model_name='academicevent',
            constraint=models.UniqueConstraint(fields=('course', 'title', 'event_type'), name='unique_event_per_course'),
        ),
        migrations.AddConstraint(
            model_name='gradeitem',
            constraint=models.UniqueConstraint(fields=('course', 'name', 'category'), name='unique_grade_item_per_course'),
        ),
        migrations.AddConstraint(
            model_name='studytool',
            constraint=models.UniqueConstraint(fields=('course', 'title', 'tool_type'), name='unique_study_tool_per_course'),
        ),
        migrations.AddConstraint(
            model_name='syllabus',
            constraint=models.UniqueConstraint(fields=('course', 'version'), name='unique_syllabus_version_per_course'),
        ),
    ]
